services:
  qdrant-test:
    image: qdrant/qdrant:latest
    container_name: wayne_qdrant_test
    ports:
      - "6333:6333"
      - "6334:6334"
  wayne_test:
    image: wayne_backend_development:latest
    container_name: wayne_backend_test
    command: /bin/sh -c "pytest --show-capture=all ${TEST_DIR} | tee /app/tests/test-log/results.log"
    environment:
      QDRANT_URL: "http://wayne_qdrant_test:6333"
      PYTHONPATH: "/app/"
      OLLAMA_RUNNING: ${OLLAMA_RUNNING}
    ports:
      - "18081:80"
    volumes:
      - ${TOP}/server/backend:/app
    depends_on:
      - qdrant-test
