[pytest]
filterwarnings =
    ignore:datetime.datetime.utcnow:DeprecationWarning:botocore
    ignore:co_lnotab is deprecated:DeprecationWarning
    ignore:Deprecated call to `pkg_resources.declare_namespace:DeprecationWarning
    ignore:pkg_resources is deprecated as an API:UserWarning
addopts = "--ignore=/app/tests/test_data"